version: "3.7"

services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: app
    ports:
      - "5436:5432"
  # Add Server here
      